config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :allergens
  #/search is the route to your search page and searches#search means your search.html.erb is located in the view folder named searches
  get '/search' => 'searches#search', as: 'search_search'
  root 'allergens#index'

  #When we use resources routes, we are mapping the browser 
  #requests (HTTP verbs and URLs) to the controller actions 
  #of our app

  # routes are mapped to: controller actions (Order of declaration matters)
  # get '/products', to: 'products#index', as: 'products_path'
  # get '/products/:id', to: 'products#show', as: 'post_path(object)'
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product_path(object)'
  # get '/products/new', to: 'products#new', as: 'new_product_path'
  # post '/products', to: 'products#create'
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'

  # resource routing maps routes to controller actions replacing code above
  # with a single line of code:   "resources :products"


end

app/views/shared/_allergen.html.erb
<% substances = allergen.substances.split(";") %>
<div id="shadow" class="panel">
  <div id="index-panel-heading" class="panel-heading">
    <div class="panel-title">
      <!-- Split button -->
      <div class="btn-group">
        <% if index_view %>
          <button type="button" id="index-panel-button" class="btn btn-primary"><%= allergen.category %></button>
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit   ", edit_allergen_path(allergen.category)%></li>
            <li><%= link_to "Delete   ", allergen_path(allergen.category), method: :delete, data: { confirm: "Are you sure you want to delete this Allergen?"}%></li>
          </ul>
        <% else %>
          <div id = "search_view">
            <button type="button" id="index-panel-button" class="btn btn-primary"><%= allergen.category %></button>
        </div>
        <% end %>
      </div>
      <!--  -->
    </div>
  </div>
  <div class="panel-body">
    <% substances.each do |substance| %>
      <div class="substances text-color-not-ok">
        <!-- if invoked from index.html display every substance in category -->
        <% if index_view %> 
          <%= substance %>
        <!-- if invoked from search, display on search match substances in category -->
        <% elsif substance.upcase.include?(search_item.upcase)%> 
          <%= highlight(substance, search_item) %>
        <% end %>
      </div> 
    <% end %>
  </div>
</div>

app/views/shared/_errors.html.erb
<!-- Rails validations are triggered when the data submissions try to hit the database.The errors are saved on the model object. When there are validation errors, they are saved to the object.errors. We display the validation messages by referencing the object.errors.full_messages method like below. By using the full_messages method, the errors are displayed in a nice, readable sentence format. -->
<!-- Here, obj must be an active record object. -->

<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this product from being saved:
          </h2>
          <!-- <div class="panel-body"> -->
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
                <% end %>
            </ul>
          <!-- </div> -->
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_product.html.erb
<% product_reactions = Reaction.where("product_id = ?", product.id) %>
<!-- for debugging... < % debug =1/0 % >  -->
  <% if index_view %>
    <tr>
  <% else %>
    <tr id="search_view">
  <% end %>
  <% if product_reactions.empty? %> <!-- product contains no allergens -->
    <td class="text-color-ok"><%= product.name %></td>
    <td class="text-color-ok"><%= product.ingredients %></td>
  <% else %> <!-- product does contains allergens -->
    <td class="text-color-not-ok"><%= product.name %></td>
    <% search_item = product_reactions.select(:reactive_ingredient).distinct.pluck(:reactive_ingredient) %>
    <td class="text-color-not-ok"><%= highlight(product.ingredients, search_item) %></td>
  <% end %>
  <% if index_view %>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Show', product_path(product) %></td>
    <td><%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: "Are you sure?"} %></td>
  <% end %>
</tr>

app/views/shared/_products_table.html.erb
<table class="table">
  <tr colspan="3">
    <th>Product</th>
    <th class='center'>Ingredients</th>
    <th class='center' colspan="3">Actions</th>
  </tr>
  <% obj.each do |item| %>
    <% item_reactions = Reaction.where("product_id = ?", item.id) %>
    <!-- for debugging... < % x=1/0 % >  -->
          <tr>
    <% if item_reactions.empty? %>

        <td class="text-color-ok"><%= item.name %></td>
        <td class="text-color-ok"><%= item.ingredients %></td>
    <% else %>
      <!-- <tr id='background-not-ok'> -->
        <td class="text-color-not-ok"><%= item.name %></td>
        <% allergic_ingredients = item_reactions.select(:reactive_ingredient).distinct.pluck(:reactive_ingredient).join(', ') %>
        <td class="text-color-not-ok"><%= item.ingredients %><strong class='color-not-ok mark'> Contains: <%=allergic_ingredients%></strong></td>
    <% end %>
      <td><%= link_to 'Edit', edit_product_path(item) %></td>
      <td><%= link_to 'Show', product_path(item) %></td>
      <td><%= link_to 'Delete', product_path(item), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>