config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :allergens
  #/search is the route to your search page and searches#search means your search.html.erb is located in the view folder named searches
  get '/search' => 'searches#search', as: 'search_search'
  root 'allergens#index'

  #When we use resources routes, we are mapping the browser 
  #requests (HTTP verbs and URLs) to the controller actions 
  #of our app

  # routes are mapped to: controller actions (Order of declaration matters)
  # get '/products', to: 'products#index', as: 'products_path'
  # get '/products/:id', to: 'products#show', as: 'post_path(object)'
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product_path(object)'
  # get '/products/new', to: 'products#new', as: 'new_product_path'
  # post '/products', to: 'products#create'
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'

  # resource routing maps routes to controller actions replacing code above
  # with a single line of code:   "resources :products"


end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Allergen-Checker", root_path, class: "navbar-brand", id:"logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li id="link-desc"><%= link_to "List All Allergens", root_path %></li>
        <li id="link-desc"><%= link_to "List All Products", products_path %></li>
        <li id="link-desc"><%= link_to "Add an Allergen", new_allergen_path %></li>
        <li id="link-desc"><%= link_to "Add a Product", new_product_path %></li>
      </ul>
      <!--  Search -->
      <%= form_tag(search_search_path, :method => "get",   
          class: 'navbar-form navbar-right') do %>  
        <div class="input-group">  
          <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
          <div class="input-group-btn">  
            <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
          </div>  
        </div>  
      <% end %>
      <!--  -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Allergen Check</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>